### ISSUE TITLE
Error al buscar contrapartida en conciliación bancaria

### ISSUE THREAD

**Issue by Danisan** [bmya/account-financial-tools#6]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_bank_statement.py", line 543, in get_move_lines_for_reconciliation_widget
    aml_recs = self.get_move_lines_for_reconciliation(partner_id=partner_id, excluded_ids=excluded_ids, str=str, offset=offset, limit=limit)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_bank_statement.py", line 584, in get_move_lines_for_reconciliation
    str_domain = self.env['account.move.line'].domain_move_lines_for_reconciliation(str=str)
  File "/mnt/extra-addons/l10n-chile-11/ingadhoc-account-financial-tools/account_document/models/account_move_line.py", line 60, in domain_move_lines_for_reconciliation
    domain = _get_domain(excluded_ids=excluded_ids, str=str)
TypeError: domain_move_lines_for_reconciliation() got an unexpected keyword argument 'excluded_ids'

**Comment by Danisan** [comment]
@vijoin necesito que revises este punto. Está relacionado con nuestro ticket interno #176

**Comment by vijoin** [comment]
Mensaje enviado por Federico:

CONCILIACION BANCARIA

**1.** Cuando quiero buscar una contrapartida usando el campo de filtro de búsqueda:

![image](https://user-images.githubusercontent.com/11879380/45325422-d27f3b00-b51e-11e8-9683-ac752ae7ff02.png)

me da el siguiente error:

> File "/mnt/extra-addons/l10n-chile-11/ingadhoc-account-financial-tools/account_document/models/account_move_line.py", line 60, in domain_move_lines_for_reconciliation
>     domain = _get_domain(excluded_ids=excluded_ids, str=str)
> TypeError: domain_move_lines_for_reconciliation() got an unexpected keyword argument 'excluded_ids'

**2.** Tampoco me deja Validar una linea del extracto asociandola a un proveedor:

![image 1](https://user-images.githubusercontent.com/11879380/45325533-2722b600-b51f-11e8-85be-71bb3221f4d4.png)

**3.** Pero si me deja cuando quiero asociar un cliente a una línea de crédito de la cartola:

![2018-09-03_18h38_02](https://user-images.githubusercontent.com/11879380/45325562-373a9580-b51f-11e8-91cf-92ed60eb06a1.png)

**Comment by vijoin** [comment]
@Danisan  ... ¿podemos crear una instancia con datos reales para replicar más fácilmente el error?

**Comment by vijoin** [comment]
Ya logré replicar el error... 

1. Instalé los módulos account_document, invoicing, account
2. configuré el diario con un tipo de documento y su sencuencia respectiva
3. creé un par de facturas
4. creé un extracto bancario con un par de movimientos
5. accedí a la interfaz de conciliación del diario banco
6. intenté hacer una búsqueda de alguna factura desde la interfaz de conciliación y me retornó el mismo error indicado por el cliente
